new changes for todos
Liavudi/user-management-backend pull request #2
Opened 2022-03-13 11:12 UTC by Liavudi

Hi i made a new changes to the delete function please, check it out.

2022-03-18 13:49 UTC, Liavudi commented on app.py
> +@app.route("/todolist/<user>/<todo_id>", methods=['DELETE'])
Delete user argument from the frontend and the delete function in the backend

2022-03-18 14:00 UTC, sahare92 requested changes
Very good!
Remove weird files added by accident (like `__pycache__/user_management.cpython-38.pyc`)
and a few more comments here

2022-03-18 14:00 UTC, sahare92 commented on app.py
>      print(input_data)
remove unnecessary prints

2022-03-18 14:00 UTC, sahare92 commented on app.py
> +    return {}
1. Whenever creating a resource - return it in the response body, like this:
{
  'data': todo_data
}

2. When creating a resource successfully - a 201 status code should be returned (https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/201)

2022-03-18 14:00 UTC, sahare92 commented on user_management.py
>      def create_todo_list(self,user_name, todo):
move to another module - todos something - choose a name

2022-03-18 14:00 UTC, sahare92 commented on user_management.py
> +            'todo': todo
```suggestion
            'text': todo

```

2022-03-18 14:00 UTC, sahare92 commented on user_management.py
> +            'username': user_name,
```suggestion
            'ownerId': user_name,

```

2022-03-18 14:00 UTC, sahare92 commented on user_management.py
> +        todo_list = self.todo_collection.find({}, {'username': 1,'todo': 1, })
make this function return todos according to a given userId
meaning, this function will receive a userId and will return all todos of that user only!

2022-03-18 14:00 UTC, sahare92 commented on user_management.py
> +            'todos': parsed_todo_list
again, change to 'data'

2022-03-25 08:26 UTC, sahare92 approved these changes

2022-05-23 05:00 UTC, merged